[build-system]
requires = ["setuptools>=75.8"]
build-backend = "setuptools.build_meta"


[project]
name = "honours-project"
version = "0.0.0"
description = "Strategic auctioning simulation"
authors = [{ name = "Khalid Belhadj", email = "khalidbelhadj124@gmail.com" }]
